server:
  port: 8090
spring:
  thymeleaf:
    #是否开启缓存，开发时可设置为 false ，默认为 true
    cache: false
    #模板文件编码
    encoding: UTF-8
    #模板文件位置
    prefix: classpath:/templates/
    #模板文件后缀
    suffix: .html
    servlet:
      #Content Type 配置
      content-type: text/html
  servlet:
    multipart:
      #是否支持批量上传（默认true)
      enabled: true
      #上传文件大小
      max-file-size: 5120MB
      #上传请求最大为10M（默认10M）
      max-request-size: 5120MB
      #文件大小阀值，当大于这个阀值时将写入到磁盘，否则存在内存中（默认值0 一般不用修改）
      file-size-threshold: 0
      #判断是否要延迟解析文件（相当于懒加载 一般不用修改）
      resolve-lazily: false
rtsp:
  #rtsp端口
  port: 3033
  #需要转换rtsp流的视频源地址
  video-path:
pool:
  #视频上传线程池大小
  corePoolSize:
ffserver:
  enabled: true